# Generated by Django 3.0.5 on 2020-07-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.CharField(default='1', max_length=200)),
                ('REGN', models.CharField(default='1', max_length=200)),
                ('NAME_B', models.CharField(default='1', max_length=200)),
                ('ROOT', models.CharField(default='1', max_length=200)),
                ('SIM_R', models.FloatField(default=1.0)),
                ('SIM_V', models.FloatField(default=1.0)),
                ('SIM_ITOGO', models.FloatField(default=1.0)),
                ('DT', models.DateField(default=16.825)),
            ],
        ),
    ]
