# Generated by Django 3.0.7 on 2020-06-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME_B', models.CharField(max_length=200)),
                ('SIM_R', models.BigIntegerField()),
                ('SIM_V', models.BigIntegerField()),
                ('SIM_ITOGO', models.BigIntegerField()),
                ('REGN', models.BigIntegerField()),
                ('DT', models.DateField()),
            ],
        ),
    ]
