# Generated by Django 3.0.7 on 2020-06-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='REGN',
            field=models.CharField(max_length=200),
        ),
    ]
