# Generated by Django 3.0.7 on 2020-06-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20200614_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='decoding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.TextField(default='1', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='tabl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='1', max_length=3000)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='DT',
            field=models.DateField(default=16.825),
        ),
        migrations.AlterField(
            model_name='post',
            name='NAME_B',
            field=models.CharField(default='1', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='REGN',
            field=models.CharField(default='1', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='SIM_ITOGO',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='SIM_R',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='SIM_V',
            field=models.BigIntegerField(default=1),
        ),
    ]
