# Generated by Django 3.0.7 on 2020-07-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20200614_1944'),
    ]

    operations = [
        migrations.DeleteModel(
            name='decoding',
        ),
        migrations.DeleteModel(
            name='tabl',
        ),
        migrations.AddField(
            model_name='post',
            name='Number',
            field=models.CharField(default='1', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='ROOT',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
