# Generated by Django 3.0.7 on 2020-07-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20200701_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='SIM_ITOGO',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='post',
            name='SIM_R',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='post',
            name='SIM_V',
            field=models.FloatField(default=1.0),
        ),
    ]
